collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.7446808
color:
  saturation: 0.9404255
  brandStrength: 0.8085107
  lightness: 0.5914894
  brandColors:
    - '#E8E8E6'
    - '#1D2042'
    - '#A2A4B3'
    - '#6D6E88'
    - '#BDBED7'
  rhythmicContrast: 0.5744681
layout_spectrum: 0.9255319
name: Hour Cycles
