collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9404255
  brandStrength: 0.793617
  lightness: 0.5914894
  brandColors:
    - '#5C5A55'
    - '#9A9BA2'
    - '#C6E0F1'
    - '#9BBC65'
    - '#DFBE9A'
  rhythmicContrast: 0.5744681
typography_spectrum: 0.7446808
layout_spectrum: 0.1595745
name: Hour Cycles
